// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: login_request.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResponse_ReturnCode int32

const (
	LoginResponse_SUCCESS LoginResponse_ReturnCode = 0
	LoginResponse_FAILED  LoginResponse_ReturnCode = 1
)

// Enum value maps for LoginResponse_ReturnCode.
var (
	LoginResponse_ReturnCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	LoginResponse_ReturnCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x LoginResponse_ReturnCode) Enum() *LoginResponse_ReturnCode {
	p := new(LoginResponse_ReturnCode)
	*p = x
	return p
}

func (x LoginResponse_ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_login_request_proto_enumTypes[0].Descriptor()
}

func (LoginResponse_ReturnCode) Type() protoreflect.EnumType {
	return &file_login_request_proto_enumTypes[0]
}

func (x LoginResponse_ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_ReturnCode.Descriptor instead.
func (LoginResponse_ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_login_request_proto_rawDescGZIP(), []int{1, 0}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UserIdentifier:
	//
	//	*LoginRequest_PhoneNumber
	//	*LoginRequest_Email
	UserIdentifier isLoginRequest_UserIdentifier `protobuf_oneof:"user_identifier"`
	Password       string                        `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_request_proto_rawDescGZIP(), []int{0}
}

func (m *LoginRequest) GetUserIdentifier() isLoginRequest_UserIdentifier {
	if m != nil {
		return m.UserIdentifier
	}
	return nil
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x, ok := x.GetUserIdentifier().(*LoginRequest_PhoneNumber); ok {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x, ok := x.GetUserIdentifier().(*LoginRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginRequest_UserIdentifier interface {
	isLoginRequest_UserIdentifier()
}

type LoginRequest_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginRequest_PhoneNumber) isLoginRequest_UserIdentifier() {}

func (*LoginRequest_Email) isLoginRequest_UserIdentifier() {}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnCode   LoginResponse_ReturnCode    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3,enum=LoginResponse_ReturnCode" json:"return_code,omitempty"`
	ResponseData *LoginResponse_ResponseData `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3,oneof" json:"response_data,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_login_request_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetReturnCode() LoginResponse_ReturnCode {
	if x != nil {
		return x.ReturnCode
	}
	return LoginResponse_SUCCESS
}

func (x *LoginResponse) GetResponseData() *LoginResponse_ResponseData {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type LoginResponse_ResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
}

func (x *LoginResponse_ResponseData) Reset() {
	*x = LoginResponse_ResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_ResponseData) ProtoMessage() {}

func (x *LoginResponse_ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_login_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_ResponseData.ProtoReflect.Descriptor instead.
func (*LoginResponse_ResponseData) Descriptor() ([]byte, []int) {
	return file_login_request_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LoginResponse_ResponseData) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

var File_login_request_proto protoreflect.FileDescriptor

var file_login_request_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x11,
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x22, 0x80, 0x02, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x45, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x1a, 0x33, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a, 0x0a, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_login_request_proto_rawDescOnce sync.Once
	file_login_request_proto_rawDescData = file_login_request_proto_rawDesc
)

func file_login_request_proto_rawDescGZIP() []byte {
	file_login_request_proto_rawDescOnce.Do(func() {
		file_login_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_request_proto_rawDescData)
	})
	return file_login_request_proto_rawDescData
}

var file_login_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_login_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_login_request_proto_goTypes = []interface{}{
	(LoginResponse_ReturnCode)(0),      // 0: LoginResponse.ReturnCode
	(*LoginRequest)(nil),               // 1: LoginRequest
	(*LoginResponse)(nil),              // 2: LoginResponse
	(*LoginResponse_ResponseData)(nil), // 3: LoginResponse.ResponseData
}
var file_login_request_proto_depIdxs = []int32{
	0, // 0: LoginResponse.return_code:type_name -> LoginResponse.ReturnCode
	3, // 1: LoginResponse.response_data:type_name -> LoginResponse.ResponseData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_login_request_proto_init() }
func file_login_request_proto_init() {
	if File_login_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_login_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_ResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_login_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LoginRequest_PhoneNumber)(nil),
		(*LoginRequest_Email)(nil),
	}
	file_login_request_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_request_proto_goTypes,
		DependencyIndexes: file_login_request_proto_depIdxs,
		EnumInfos:         file_login_request_proto_enumTypes,
		MessageInfos:      file_login_request_proto_msgTypes,
	}.Build()
	File_login_request_proto = out.File
	file_login_request_proto_rawDesc = nil
	file_login_request_proto_goTypes = nil
	file_login_request_proto_depIdxs = nil
}
