// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: register_request.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterResponse_ReturnCode int32

const (
	RegisterResponse_SUCCESS     RegisterResponse_ReturnCode = 0
	RegisterResponse_PHONE_TAKEN RegisterResponse_ReturnCode = 1
	RegisterResponse_EMAIL_TAKEN RegisterResponse_ReturnCode = 2
)

// Enum value maps for RegisterResponse_ReturnCode.
var (
	RegisterResponse_ReturnCode_name = map[int32]string{
		0: "SUCCESS",
		1: "PHONE_TAKEN",
		2: "EMAIL_TAKEN",
	}
	RegisterResponse_ReturnCode_value = map[string]int32{
		"SUCCESS":     0,
		"PHONE_TAKEN": 1,
		"EMAIL_TAKEN": 2,
	}
)

func (x RegisterResponse_ReturnCode) Enum() *RegisterResponse_ReturnCode {
	p := new(RegisterResponse_ReturnCode)
	*p = x
	return p
}

func (x RegisterResponse_ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterResponse_ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_register_request_proto_enumTypes[0].Descriptor()
}

func (RegisterResponse_ReturnCode) Type() protoreflect.EnumType {
	return &file_register_request_proto_enumTypes[0]
}

func (x RegisterResponse_ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterResponse_ReturnCode.Descriptor instead.
func (RegisterResponse_ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_register_request_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsVolunteer         bool                                 `protobuf:"varint,1,opt,name=is_volunteer,json=isVolunteer,proto3" json:"is_volunteer,omitempty"`
	FirstName           string                               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName            string                               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password            string                               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Address             *HomeAddress                         `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber         string                               `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IdNumber            string                               `protobuf:"bytes,7,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Birthday            *Date                                `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	FcmToken            *string                              `protobuf:"bytes,9,opt,name=fcm_token,json=fcmToken,proto3,oneof" json:"fcm_token,omitempty"`
	VolunteerParameters *RegisterRequest_VolunteerParameters `protobuf:"bytes,10,opt,name=volunteer_parameters,json=volunteerParameters,proto3,oneof" json:"volunteer_parameters,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_register_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_register_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_register_request_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetIsVolunteer() bool {
	if x != nil {
		return x.IsVolunteer
	}
	return false
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetAddress() *HomeAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *RegisterRequest) GetBirthday() *Date {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *RegisterRequest) GetFcmToken() string {
	if x != nil && x.FcmToken != nil {
		return *x.FcmToken
	}
	return ""
}

func (x *RegisterRequest) GetVolunteerParameters() *RegisterRequest_VolunteerParameters {
	if x != nil {
		return x.VolunteerParameters
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnCode   RegisterResponse_ReturnCode    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3,enum=RegisterResponse_ReturnCode" json:"return_code,omitempty"`
	ResponseData *RegisterResponse_ResponseData `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3,oneof" json:"response_data,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_register_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_register_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_register_request_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetReturnCode() RegisterResponse_ReturnCode {
	if x != nil {
		return x.ReturnCode
	}
	return RegisterResponse_SUCCESS
}

func (x *RegisterResponse) GetResponseData() *RegisterResponse_ResponseData {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type RegisterRequest_VolunteerParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RegisterRequest_VolunteerParameters) Reset() {
	*x = RegisterRequest_VolunteerParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_register_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest_VolunteerParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest_VolunteerParameters) ProtoMessage() {}

func (x *RegisterRequest_VolunteerParameters) ProtoReflect() protoreflect.Message {
	mi := &file_register_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest_VolunteerParameters.ProtoReflect.Descriptor instead.
func (*RegisterRequest_VolunteerParameters) Descriptor() ([]byte, []int) {
	return file_register_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegisterRequest_VolunteerParameters) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse_ResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
}

func (x *RegisterResponse_ResponseData) Reset() {
	*x = RegisterResponse_ResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_register_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse_ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse_ResponseData) ProtoMessage() {}

func (x *RegisterResponse_ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_register_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse_ResponseData.ProtoReflect.Descriptor instead.
func (*RegisterResponse_ResponseData) Descriptor() ([]byte, []int) {
	return file_register_request_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RegisterResponse_ResponseData) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

var File_register_request_proto protoreflect.FileDescriptor

var file_register_request_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xeb, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6e,
	0x74, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x56, 0x6f,
	0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x26, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x64, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x09, 0x66, 0x63,
	0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x66, 0x63, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x5c, 0x0a, 0x14,
	0x76, 0x6f, 0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x6f, 0x6c,
	0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x48, 0x01, 0x52, 0x13, 0x76, 0x6f, 0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x88, 0x01, 0x01, 0x1a, 0x2b, 0x0a, 0x13, 0x56, 0x6f,
	0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x66, 0x63, 0x6d, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6e, 0x74,
	0x65, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x9f,
	0x02, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x1a, 0x33, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x3b, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x50, 0x48, 0x4f, 0x4e, 0x45, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x02, 0x42, 0x10,
	0x0a, 0x0e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_register_request_proto_rawDescOnce sync.Once
	file_register_request_proto_rawDescData = file_register_request_proto_rawDesc
)

func file_register_request_proto_rawDescGZIP() []byte {
	file_register_request_proto_rawDescOnce.Do(func() {
		file_register_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_register_request_proto_rawDescData)
	})
	return file_register_request_proto_rawDescData
}

var file_register_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_register_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_register_request_proto_goTypes = []interface{}{
	(RegisterResponse_ReturnCode)(0),            // 0: RegisterResponse.ReturnCode
	(*RegisterRequest)(nil),                     // 1: RegisterRequest
	(*RegisterResponse)(nil),                    // 2: RegisterResponse
	(*RegisterRequest_VolunteerParameters)(nil), // 3: RegisterRequest.VolunteerParameters
	(*RegisterResponse_ResponseData)(nil),       // 4: RegisterResponse.ResponseData
	(*HomeAddress)(nil),                         // 5: HomeAddress
	(*Date)(nil),                                // 6: Date
}
var file_register_request_proto_depIdxs = []int32{
	5, // 0: RegisterRequest.address:type_name -> HomeAddress
	6, // 1: RegisterRequest.birthday:type_name -> Date
	3, // 2: RegisterRequest.volunteer_parameters:type_name -> RegisterRequest.VolunteerParameters
	0, // 3: RegisterResponse.return_code:type_name -> RegisterResponse.ReturnCode
	4, // 4: RegisterResponse.response_data:type_name -> RegisterResponse.ResponseData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_register_request_proto_init() }
func file_register_request_proto_init() {
	if File_register_request_proto != nil {
		return
	}
	file_user_information_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_register_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_register_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_register_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest_VolunteerParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_register_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse_ResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_register_request_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_register_request_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_register_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_register_request_proto_goTypes,
		DependencyIndexes: file_register_request_proto_depIdxs,
		EnumInfos:         file_register_request_proto_enumTypes,
		MessageInfos:      file_register_request_proto_msgTypes,
	}.Build()
	File_register_request_proto = out.File
	file_register_request_proto_rawDesc = nil
	file_register_request_proto_goTypes = nil
	file_register_request_proto_depIdxs = nil
}
